package com.taurilogs.app.enums

import com.taurilogs.app.R

enum class SpecEnum(val value: Int, val resourceId: Int) {
    WARRIOR_ARMS(71, R.drawable.warrior_arms),
    WARRIOR_FURY(72, R.drawable.warrior_fury),
    WARRIOR_PROTECTION(73, R.drawable.warrior_protection),
    PALADIN_HOLY(65, R.drawable.paladin_holy),
    PALADIN_PROTECTION(66, R.drawable.paladin_protection),
    PALADIN_RETRIBUTION(70, R.drawable.paladin_retribution),
    HUNTER_MARKSMANSHIP(254, R.drawable.hunter_marksmanship),
    HUNTER_BM(253, R.drawable.hunter_bm),
    HUNTER_SURVIVAL(255, R.drawable.hunter_survival),
    ROGUE_ASSASSINATION(259, R.drawable.rogue_assassination),
    ROGUE_COMBAT(260, R.drawable.rogue_combat),
    ROGUE_SUBTLETY(261, R.drawable.rogue_subtlety),
    PRIEST_DISCO(256, R.drawable.priest_disco),
    PRIEST_HOLY(257, R.drawable.priest_holy),
    PRIEST_SHADOW(258, R.drawable.priest_shadow),
    DK_BLOOD(250, R.drawable.dk_blood),
    DK_FROST(251, R.drawable.dk_frost),
    DK_UNHOLY(252, R.drawable.dk_unholy),
    SHAMAN_ELEMENTAL(262, R.drawable.shaman_elemental),
    SHAMAN_ENHANCEMENT(263, R.drawable.shaman_enhancement),
    SHAMAN_RESTORATION(264, R.drawable.shaman_restoration),
    MAGE_FROST(64, R.drawable.mage_frost),
    MAGE_FIRE(63, R.drawable.mage_fire),
    MAGE_ARCANE(62, R.drawable.mage_arcane),
    WARLOCK_AFFLICTION(265, R.drawable.warlock_affliction),
    WARLOCK_DEMONOLOGY(266, R.drawable.warlock_demonology),
    WARLOCK_DESTRUCTION(267, R.drawable.warlock_destruction),
    MONK_MISTWEAVER(270, R.drawable.monk_mistweaver),
    MONK_WINDWALKER(269, R.drawable.monk_windwalker),
    MONK_BREWMASTER(268, R.drawable.monk_brewmaster),
    DRUID_RESTORATION(105, R.drawable.druid_restoration),
    DRUID_GUARDIAN(104, R.drawable.druid_guardian),
    DRUID_FERAL(103, R.drawable.druid_feral),
    DRUID_BALANCE(102, R.drawable.druid_balance);
}
